# Generated by Django 5.1.7 on 2025-03-14 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.CharField(choices=[('YEAR_1', 'YEAR_1'), ('YEAR_2', 'YEAR_2'), ('YEAR_3', 'YEAR_3'), ('YEAR_4', 'YEAR_4'), ('YEAR_5', 'YEAR_5')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=models.TextField(help_text='Describe the issue in not more than 500 characters', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
