# Generated by Django 5.1.6 on 2025-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.CharField(choices=[('YEAR 1', 'YEAR 1'), ('YEAR_2', 'YEAR 2'), ('YEAR_3', 'YEAR 3'), ('YEAR_4', 'YEAR 4'), ('YEAR_5', 'YEAR 5')], max_length=20, null=True),
        ),
    ]
