# Generated by Django 4.2.20 on 2025-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('missingmarks', 'MISSING MARKS'), ('appeal', 'APPEAL'), ('correction', 'CORRECTION')], max_length=50),
        ),
    ]
