# Generated by Django 5.2 on 2025-04-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers_alter_lecturer_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type',
            new_name='category',
        ),
    ]
