# Generated by Django 5.1.7 on 2025-03-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_issue_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.department'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='course_unit_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
