# Generated by Django 5.1.7 on 2025-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_year_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Default_Name', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='term_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
