# Generated by Django 5.1.6 on 2025-03-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit_name', models.CharField(max_length=100)),
                ('course_unit_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(choices=[('Student', 'STUDENT'), ('Lecturer', 'LECTURER'), ('Academic_registrar', 'ACADEMIC REGISTRAR')], default='Student', max_length=40),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_marks', 'MISSING MARKS'), ('appeal', 'APPEAL'), ('correction', 'CORRECTION')], max_length=50)),
                ('issue_status', models.CharField(choices=[('Pending', 'PENDING'), ('Resolved', 'RESOLVED'), ('In Progress', 'IN PROGRESS')], default='Pending', max_length=50)),
                ('issue_description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('course_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.courseunit')),
                ('lecturer', models.ForeignKey(limit_choices_to={'Role': 'Lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_issues', to=settings.AUTH_USER_MODEL)),
                ('registrar', models.ForeignKey(limit_choices_to={'Role': 'Academic_registrar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['update', 'date_created'],
            },
        ),
    ]
