# Generated by Django 5.1.7 on 2025-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_full_name_customuser_term_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'SEMESTER 1'), ('Semester 2', 'SEMESTER 2')], default='Semester 1', max_length=30),
        ),
    ]
