# Generated by Django 5.2 on 2025-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_issue_type_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester One'), ('2', 'Semester Two')], max_length=50),
        ),
    ]
