# Generated by Django 5.2 on 2025-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_issue_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('missingmarks', 'MISSING MARKS'), ('appeal', 'APPEAL'), ('correction', 'CORRECTION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='office_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
