# Generated by Django 5.2 on 2025-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_enrollment_date_alter_issue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='staff_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='staff_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
