# Generated by Django 5.1.6 on 2025-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_image_alter_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=30),
        ),
    ]
