# Generated by Django 5.1.6 on 2025-03-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_issue_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='course_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courseunit'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('course_units', models.ManyToManyField(related_name='course_units', to='api.courseunit')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.program'),
        ),
    ]
