# Generated by Django 4.2.20 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
